### ISSUE TITLE
Error en Laravel

### ISSUE THREAD

**Issue by AndresReyesDev** [LibreDTE/libredte-sdk-php#3]
Hola!

Estoy recibiendo un error en al tratar de generar documentos. Esto funcionaba OK hasta hace 5 días aproximadamente. Al revisar el log de laravel el mensaje es este:

```
[2018-11-12 13:59:55] local.ERROR: Undefined offset: 2 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 2 at /home/reservas/subdomains/payment.reservaschilepsicologos.com/vendor/sasco/libredte-sdk-php/sdk/Network/Http/Socket.php:155)
[stacktrace]
#0 /home/reservas/subdomains/payment.reservaschilepsicologos.com/vendor/sasco/libredte-sdk-php/sdk/Network/Http/Socket.php(155): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/home/reservas/...', 155, Array)
#1 /home/reservas/subdomains/payment.reservaschilepsicologos.com/vendor/sasco/libredte-sdk-php/sdk/Network/Http/Socket.php(98): sasco\\LibreDTE\\SDK\\Network\\Http\\Socket::parseStatus('HTTP/2 200')
#2 /home/reservas/subdomains/payment.reservaschilepsicologos.com/vendor/sasco/libredte-sdk-php/sdk/Network/Http/Rest.php(114): sasco\\LibreDTE\\SDK\\Network\\Http\\Socket::__callStatic('POST', Array)
#3 /home/reservas/subdomains/payment.reservaschilepsicologos.com/vendor/sasco/libredte-sdk-php/sdk/LibreDTE.php(86): sasco\\LibreDTE\\SDK\\Network\\Http\\Rest->__call('post', Array)
#4 /home/reservas/subdomains/payment.reservaschilepsicologos.com/app/Http/Controllers/TransactionController.php(205): sasco\\LibreDTE\\SDK\\LibreDTE->post('/dte/documentos...', Array)
```

**Comment by estebandelaf** [comment]
En esta línea (155 de Socket.php):

`list($protocol, $status, $message) = explode(' ', $response_line, 3);`

El mensaje indica que no existiría el $message (en realidad no está el índice en el arreglo para obtener el $message). Esto sólo podría pasar porque la línea de respuesta con el estado viniese diferente. Pero no hemos tenido problema en la versión oficial (que también hace todo consumiendo los mismos servicios web).

Por favor, podrías antes de la línea 155:

https://github.com/LibreDTE/libredte-sdk-php/blob/master/sdk/Network/Http/Socket.php#L155

Agregar un log para la variable `$response_line` y enviar el contenido de esa variable acá por favor (para ver cómo es la respuesta que estás teniendo en esa línea).

**Comment by estebandelaf** [comment]
También sería útil ver el contenido de esto (línea 95):

`substr($response, 0, $header_size)`

**Comment by AndresReyesDev** [comment]
El log solicitado:

```
[2018-11-12 20:07:11] local.DEBUG: +++++++++++++  
[2018-11-12 20:07:11] local.DEBUG: **Variable $header**

[2018-11-12 20:07:11] local.DEBUG: array (
  0 => 'HTTP/2 200',
  'date' => 'Mon, 12 Nov 2018 20:07:11 GMT',
  'content-type' => 'application/json; charset=utf-8',
  'set-cookie' => 
  array (
    0 => '__cfduid=d5c9dcb67f43f2bcec24a46084d5bc02e1542053230; expires=Tue, 12-Nov-19 20:07:10 GMT; path=/; domain=.libredte.cl; HttpOnly',
    1 => 'sec_session_id=a3eth4f1ts9amlcdk19lp7e861; expires=Tue, 13-Nov-2018 06:07:08 GMT; Max-Age=36000; path=/; domain=libredte.cl; secure; HttpOnly',
    2 => 'sec_session_id=a3eth4f1ts9amlcdk19lp7e861; expires=Tue, 13-Nov-2018 06:07:08 GMT; Max-Age=36000; path=/; domain=libredte.cl; secure; HttpOnly',
  ),
  'expires' => 'Thu, 19 Nov 1981 08:52:00 GMT',
  'cache-control' => 'no-store, no-cache, must-revalidate',
  'pragma' => 'no-cache',
  'vary' => 'Accept-Encoding',
  'expect-ct' => 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  'server' => 'cloudflare',
  'cf-ray' => '478b9f94dd337ae2-MCI',
)  

[2018-11-12 20:07:11] local.DEBUG: +++++++++++++  
[2018-11-12 20:07:11] local.DEBUG: **Valor del substr($response, 0, $header_size)**
[2018-11-12 20:07:11] local.DEBUG: HTTP/2 200 
date: Mon, 12 Nov 2018 20:07:11 GMT
content-type: application/json; charset=utf-8
set-cookie: __cfduid=d5c9dcb67f43f2bcec24a46084d5bc02e1542053230; expires=Tue, 12-Nov-19 20:07:10 GMT; path=/; domain=.libredte.cl; HttpOnly
set-cookie: sec_session_id=a3eth4f1ts9amlcdk19lp7e861; expires=Tue, 13-Nov-2018 06:07:08 GMT; Max-Age=36000; path=/; domain=libredte.cl; secure; HttpOnly
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
set-cookie: sec_session_id=a3eth4f1ts9amlcdk19lp7e861; expires=Tue, 13-Nov-2018 06:07:08 GMT; Max-Age=36000; path=/; domain=libredte.cl; secure; HttpOnly
vary: Accept-Encoding
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 478b9f94dd337ae2-MCI


[2018-11-12 20:07:11] local.DEBUG: +++++++++++++  
[2018-11-12 20:07:11] local.DEBUG: **Variable $response_line**  
[2018-11-12 20:07:11] local.DEBUG: HTTP/2 200  
[2018-11-12 20:07:11] local.DEBUG: +++++++++++++  
```

Quedo atento

**Comment by estebandelaf** [comment]
Estás haciendo la conexión usando HTTP/2, y en este no está el mensaje del estado (eso ocasionaba el error).

Se hizo un cambio para procesar sólo el protocolo y el código, y el mensaje ahora es opcional (sólo si viene). Actualiza el SDK ;-)

Si puede confirmar que ahora está ok, genial!

**Comment by AndresReyesDev** [comment]
Lamentablemente muestra el mismo error. Acabo de realizar la prueba.

**Comment by estebandelaf** [comment]
Lo probé ayer emulando la respuesta como: HTTP/2 200

La respuesta en HTTP/1.1 es HTTP/1.1 200 Ok (por eso el explode hacia 3 cortes). Ahora se hacen 3, pero si no hay 3 dejará 2 y se verifica luego.

¿100% seguro qué es el mismo error? y ¿100% seguro qué el archivo está actualizado a este commit https://github.com/LibreDTE/libredte-sdk-php/commit/829c8170d35e6036fc81da27b2e5c759924ae285 ?

**Comment by AndresReyesDev** [comment]
Perfecto! Ahora funcionó!

No había funcionado anteriormente ya que no había actualizado el Socket.php (usé composer update y no actualizó ya que no era una nueva versión).

Gracias!

**Comment by estebandelaf** [comment]
Ups, olvidé crear la versión para que apareciera en composer :D ¡ahora lo hice!

**Comment by AndresReyesDev** [comment]
Excelente! Muchas gracias!! 👏
